project:
  type: website
  output-dir: docs

website:
  title: "Sano Tanna"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd

      
format:
  html:
    page-layout: full
    theme:
      dark: darkly
      light: minty
    css: styles.css
    toc: true

editor: visual

